import {AmbientLight,AnimationMixer,Box3,BoxGeometry,Color,CylinderGeometry,DirectionalLight,Fog,Group,Mesh,MeshBasicMaterial,PerspectiveCamera,PointLight,Scene,SphereGeometry,TorusGeometry,Vector3,type Texture,type WebGLRenderer} from 'three';
import type {GLTF} from 'three/addons/loaders/GLTFLoader.js';
import type {CampaignSave} from './CampaignSave';
import type {ManagedScene} from './SceneController';
import {CommsPanel} from './CommsPanel';
import {disposeObject} from './ModelAssets';
import {BOO_POSITION,FEED_NAMES,FOG_COMMS,FOG_GUARDS,FOG_LANDING,FOG_RELAYS,completeFogCitadel,fogClear,fogSpawn,meetBoo,nearFog,resolveFogRelay} from './FogMoon';
import {CITADEL,FogCitadel} from './FogCitadel';
import {SurfaceInput,bindSurfaceButton} from './SurfaceInput';
import {SurfaceDash} from './SurfaceDash';
import {SpectralReveal} from './SpectralReveal';
import {fieldRepair,slideSurface,surfaceSegmentHit} from './SurfaceCombat';
import {segmentSphere} from './SpaceGeometry';
import {frameConversation} from './ConversationFrame';
import {frameWarden} from './WardenFrame';
import {fighterFootprint,withinFootprint,type GroundPoint} from './FighterFootprint';
import {PARKED_HEIGHT} from './LandingPlan';
import {sfx} from '../audio/Sfx';
import './surface.css';
interface Host{renderer:WebGLRenderer;environment:Texture;root:HTMLElement;save:CampaignSave;models:GLTF[];arrival:boolean;onOrbit:()=>void;onRetry:()=>void}
interface Guard{mesh:Group;sector:string;hp:number;wait:number;charge:number;target:Vector3;tell:Mesh}
interface Shot{mesh:Mesh;velocity:Vector3;hostile:boolean;life:number}
/** Connected lunar relay route: physical actors, retained clues, real feed hits. */
export class FogMoonScene implements ManagedScene{
  private readonly scene=new Scene();private readonly camera=new PerspectiveCamera(46,1,.1,350);private readonly sun=new DirectionalLight(0xc8d7ff,2.9);
  private readonly ui=document.createElement('section');private readonly status=document.createElement('p');private readonly hint=document.createElement('p');private readonly notice=document.createElement('p');
  private readonly fire=document.createElement('button');private readonly pauseButton=document.createElement('button');private readonly repairButton=document.createElement('button');private readonly shieldButton=document.createElement('button');private readonly dashButton=document.createElement('button');private readonly revealButton=document.createElement('button');private readonly interactButton=document.createElement('button');
  private readonly lifetime=new AbortController();private readonly input:SurfaceInput;private readonly comms:CommsPanel;private readonly hero:Group;private readonly boo:Group;private readonly boss:Group;private readonly fighter:Group;private readonly fighterOutline:readonly GroundPoint[];private readonly mixer:AnimationMixer;private readonly booMixer:AnimationMixer;
  private readonly battle=new FogCitadel();private readonly dash=new SurfaceDash();private readonly reveal=new SpectralReveal();private readonly guards:Guard[]=[];private readonly shots:Shot[]=[];private readonly hazards=new Map<number,Mesh>();private readonly learned=new Set<number>();
  private readonly green=new MeshBasicMaterial({color:0x00ff00,toneMapped:false});private readonly red=new MeshBasicMaterial({color:0xff2200,toneMapped:false});private readonly dark=new MeshBasicMaterial({color:0x281719});private readonly ball=new SphereGeometry(.085,8,6);private readonly box=new BoxGeometry(1,1,1);private readonly circle=new CylinderGeometry(1,1,.02,24);
  private readonly revealRing=new Mesh(new TorusGeometry(1,.018,5,64),this.green);private readonly targetRing=new Mesh(new TorusGeometry(1.2,.055,6,32),this.green);private readonly shield=new Mesh(new SphereGeometry(1,16,10),new MeshBasicMaterial({color:0x00ff00,wireframe:true,transparent:true,opacity:.18,toneMapped:false}));
  private readonly feedLabels:HTMLSpanElement[]=[];private readonly bossBounds:Box3;private relayPanel:HTMLElement|null=null;private restored=false;private factionApplied=false;private met=false;private started=false;private active=false;private paused=false;private dead=false;private pending=false;private talking=false;private talkKind:keyof typeof FOG_COMMS='boo';private arrival=0;
  private life=100;private charge=100;private shielding=false;private repairCooldown=0;private invulnerable=0;private fireClock=0;private noticeClock=0;private age=0;private hudClock=0;private clip='';private dashing=false;private shotsFired=0;private hits=0;private injuries=0;
  constructor(private readonly host:Host){
    const [hero,boo,fighter,terrain,boss,drone]=host.models;this.hero=hero.scene;this.boo=boo.scene;this.fighter=fighter.scene;this.boss=boss.scene;this.mixer=new AnimationMixer(this.hero);this.booMixer=new AnimationMixer(this.boo);
    for(const name of ['Boo_Origin','Face_Focus','Pulse_Origin','Tail_Anchor'])if(!this.boo.getObjectByName(name))throw Error('Missing Boo attachment: '+name);
    for(const name of ['Feed_0','Feed_1','Feed_2','Reflector_0','Reflector_1','Reflector_2'])if(!this.boss.getObjectByName(name))throw Error('Missing Citadel attachment: '+name);
    for(const r of FOG_RELAYS)for(let i=0;i<3;i++)if(!terrain.scene.getObjectByName(`Relay_${r.id}_Feed_${i}`))throw Error('Missing relay feed');
    const spawn=fogSpawn(host.save);this.hero.position.set(spawn.x,0,spawn.z);this.boo.position.set(BOO_POSITION.x,0,BOO_POSITION.z);this.boo.rotation.y=.1;this.boss.position.z=-48;this.bossBounds=new Box3().setFromObject(this.boss);
    this.arrival=host.arrival?4:0;this.fighter.position.set(0,PARKED_HEIGHT,34);this.fighterOutline=fighterFootprint(this.fighter);this.fighter.position.y+=this.arrival?8:0;this.hero.visible=!this.arrival;const canopy=this.fighter.getObjectByName('Canopy_Hinge');if(canopy)canopy.rotation.x=-1.15;
    this.met=host.save.snapshot.quests.includes('fog_moon.boo_met');this.restored=host.save.snapshot.quests.includes('fog_moon.restored');if(this.restored)this.battle.hp=0;this.paused=host.save.testSlot;
    this.scene.background=new Color(0x191a29);this.scene.fog=new Fog(0x29273c,48,155);this.scene.environment=host.environment;this.scene.environmentIntensity=.48;this.scene.add(this.hero,this.boo,this.fighter,terrain.scene,this.boss,new AmbientLight(0xa2afce,.65));
    this.sun.castShadow=true;this.sun.shadow.mapSize.set(1024,1024);Object.assign(this.sun.shadow.camera,{left:-19,right:19,top:19,bottom:-19,near:1,far:100});this.sun.shadow.camera.updateProjectionMatrix();this.sun.shadow.bias=-.0003;this.sun.shadow.normalBias=.035;this.scene.add(this.sun,this.sun.target);
    const halo=new PointLight(0x00ff00,4,6,2);halo.position.y=1;this.hero.add(halo);const booHalo=new Mesh(new TorusGeometry(.48,.015,6,32),this.green);booHalo.rotation.x=Math.PI/2;booHalo.position.set(BOO_POSITION.x,.08,BOO_POSITION.z);this.scene.add(booHalo);
    const library=new Group();library.visible=false;library.add(drone.scene,new Mesh(this.ball,this.red),new Mesh(this.box,this.dark),new Mesh(this.circle,this.green));const materials=new Set<import('three').Material>();for(const m of host.models)m.scene.traverse(o=>{if(o instanceof Mesh)for(const mat of Array.isArray(o.material)?o.material:[o.material])materials.add(mat);});for(const m of materials)library.add(new Mesh(this.ball,m));this.scene.add(library);
    for(const [i,g] of FOG_GUARDS.entries()){
      if(this.restored||g.sector==='shelter'&&this.met||host.save.snapshot.quests.includes('fog_moon.relay.'+g.sector))continue;
      const mesh=drone.scene.clone(true);mesh.scale.setScalar(.11);mesh.position.set(g.x,1.1,g.z);this.scene.add(mesh);const tell=new Mesh(this.circle,new MeshBasicMaterial({color:0xff2200,transparent:true,opacity:.35,toneMapped:false,depthWrite:false}));tell.visible=false;this.scene.add(tell);this.guards.push({mesh,sector:g.sector,hp:60,wait:1.3+i*.55,charge:0,target:new Vector3(),tell});
    }
    this.revealRing.rotation.x=Math.PI/2;this.revealRing.visible=false;this.targetRing.visible=false;this.shield.scale.set(.8,1.05,.8);this.shield.visible=false;this.scene.add(this.revealRing,this.targetRing,this.shield);
    this.scene.traverse(o=>{if(o instanceof Mesh){o.castShadow=true;o.receiveShadow=true;for(const m of Array.isArray(o.material)?o.material:[o.material])if(/Liquidity|#00FF00|#FF2200/.test(m.name))m.toneMapped=false;}});
    this.ui.className='surface-ui fog-ui';this.comms=new CommsPanel(this.ui);this.buildUI();this.input=new SurfaceInput(host.renderer.domElement,this.fire,()=>this.canAct(),{interact:()=>this.interact(),pause:()=>this.togglePause(),repair:()=>this.repair(),shield:()=>this.toggleShield(),dash:()=>this.startDash(),reveal:()=>this.pulse()});
    window.addEventListener('blur',this.pause,{signal:this.lifetime.signal});document.addEventListener('visibilitychange',()=>{if(document.hidden)this.pause();},{signal:this.lifetime.signal});this.booAnimation('Idle');this.play('Idle');this.refresh();this.updateCamera(true);this.paint();
  }
  private buildUI():void{
    this.status.className='surface-status';this.hint.className='surface-hint';this.notice.className='surface-message';const top=document.createElement('div');top.className='surface-top';const bottom=document.createElement('div');bottom.className='surface-actions';
    const action=(b:HTMLButtonElement,label:string,run:()=>void,parent:HTMLElement)=>{b.type='button';b.textContent=label;bindSurfaceButton(b,()=>{if(this.active)run();},this.lifetime.signal);parent.appendChild(b);};
    action(this.pauseButton,'PAUSE',()=>this.togglePause(),top);const ship=document.createElement('button');action(ship,'WARSHIP',()=>this.returnShip(),top);
    action(this.shieldButton,'SHIELD',()=>this.toggleShield(),bottom);action(this.repairButton,'REPAIR',()=>this.repair(),bottom);action(this.dashButton,'DASH',()=>this.startDash(),bottom);action(this.revealButton,'REVEAL',()=>this.pulse(),bottom);action(this.interactButton,'INTERACT',()=>this.interact(),bottom);action(this.fire,'BLAST',()=>{},bottom);this.fire.className='surface-fire';
    for(let i=0;i<3;i++){const label=document.createElement('span');label.className='fog-feed-label';label.textContent=FEED_NAMES[i];this.feedLabels.push(label);this.ui.appendChild(label);}
    this.ui.append(this.status,this.hint,top,this.notice,bottom);this.ui.hidden=true;this.host.root.appendChild(this.ui);
  }
  private canAct():boolean{return this.active&&!this.paused&&!this.dead&&!this.pending&&!this.comms.active&&!this.relayPanel&&this.arrival===0;}
  setActive(value:boolean):void{this.active=value;this.ui.hidden=!value;this.input.setActive(value);this.comms.setActive(value);window.dispatchEvent(new CustomEvent('coded:music-cue',{detail:{cue:value?'transit':'silence'}}));}
  saveBeforeLeave():boolean{return !this.pending;}
  private readonly pause=():void=>{if(this.active){this.paused=true;this.input.clear();this.paint();}};
  private togglePause():void{if(!this.active||this.dead||this.pending||this.comms.active)return;this.paused=!this.paused;this.input.clear();this.paint();}
  private say(text:string):void{this.notice.textContent=text;this.noticeClock=8;}
  private talk(kind:keyof typeof FOG_COMMS,commit:()=>boolean):void{this.talkKind=kind;this.input.clear();this.play('Idle');this.booAnimation('Interact');this.comms.open(FOG_COMMS[kind],()=>{const ok=commit();this.input.clear();if(ok){this.booAnimation('Idle');this.refresh();this.paint();}return ok;});}
  private returnShip():void{if(!this.canAct())return;if(!nearFog(this.hero.position,FOG_LANDING)){this.say('Return to the green landing beacons in the south.');return;}this.input.clear();this.host.onOrbit();}
  private solved(index:number):boolean{return this.host.save.snapshot.quests.includes('fog_moon.relay.'+FOG_RELAYS[index].id);}
  private remaining(sector:string):number{return this.guards.filter(g=>g.hp>0&&g.sector===sector).length;}
  private interact():void{
    if(!this.canAct())return;if(nearFog(this.hero.position,FOG_LANDING)){this.returnShip();return;}
    if(nearFog(this.hero.position,BOO_POSITION)){if(this.remaining('shelter')){this.say('Clear the red drones around Boo first.');return;}this.talk('boo',()=>{const result=meetBoo(this.host.save,this.hero.position,0);if(result.ok)this.met=true;return result.ok;});return;}
    const index=FOG_RELAYS.findIndex(r=>nearFog(this.hero.position,{x:r.x,z:r.z+3}));
    if(index<0){this.say(this.met?'Trace the west archive, then follow its uplink east.':'Find Boo beside the scout shelter.');return;}const r=FOG_RELAYS[index];
    if(this.solved(index)){this.say(`${r.label} · ${FEED_NAMES[r.trueFeed]} verified. Public link retained.`);return;}if(!this.met||index===1&&!this.solved(0)){this.say(index===1?'The west archive contains this uplink key.':'Boo can read these feeds. Find him first.');return;}if(this.remaining(r.id)){this.say('Clear the nearby relay guards before accessing the console.');return;}
    if(!this.learned.has(index)){this.say('Use REVEAL nearby. Follow the green trace to its letter and shape.');return;}
    this.input.clear();const panel=document.createElement('section');panel.className='boarding-shop fog-relay-choice';const text=document.createElement('p');text.textContent=`${r.label} · Genuine feed: ${FEED_NAMES[r.trueFeed]}. Route only the verified source.`;panel.appendChild(text);
    for(let feed=0;feed<3;feed++){const b=document.createElement('button');b.type='button';b.textContent=FEED_NAMES[feed];bindSurfaceButton(b,()=>{if(!this.active||this.paused)return;const result=resolveFogRelay(this.host.save,index,feed,this.hero.position,this.remaining(r.id),this.learned.has(index));if(!result.ok){text.textContent=feed!==r.trueFeed?'False signature rejected. Follow the verified '+FEED_NAMES[r.trueFeed]+'.':'The relay checkpoint could not save. Retry the verified feed.';return;}panel.remove();this.relayPanel=null;this.input.clear();this.refresh();this.say(index===0?'WEST ARCHIVE VERIFIED · Follow the north loop to the east uplink.':'UPLINK VERIFIED · The Citadel is exposed to the north.');},this.lifetime.signal);panel.appendChild(b);}
    const close=document.createElement('button');close.type='button';close.textContent='CLOSE';bindSurfaceButton(close,()=>{panel.remove();this.relayPanel=null;this.input.clear();},this.lifetime.signal);panel.appendChild(close);this.relayPanel=panel;this.ui.appendChild(panel);
  }
  private pulse():void{if(this.canAct()&&this.reveal.request(!!this.host.save.snapshot.heroUpgrades.spectral_reveal)){sfx.play('pulse',.65);this.say('REVEAL · Follow the genuine letter and shape.');}}
  private toggleShield():void{if(this.canAct()&&this.host.save.snapshot.heroUpgrades.ledger_shield)this.shielding=!this.shielding;}
  private repair():void{if(!this.canAct())return;const r=fieldRepair(this.life,this.repairCooldown,!!this.host.save.snapshot.heroUpgrades.field_repair);if(r.used){this.life=r.life;this.repairCooldown=r.cooldown;sfx.play('pulse',.5);}}
  private startDash():void{if(!this.canAct())return;const m=this.input.move;this.dash.request(!!this.host.save.snapshot.heroUpgrades.liquidity_dash,Math.hypot(m.x,m.y)>.1?{x:m.x,z:m.y}:{x:Math.sin(this.hero.rotation.y),z:Math.cos(this.hero.rotation.y)});}
  private play(name:string):void{if(name===this.clip)return;const clip=this.host.models[0].animations.find(a=>a.name===name);if(!clip)return;const next=this.mixer.clipAction(clip).reset().play(),old=this.host.models[0].animations.find(a=>a.name===this.clip);if(old)this.mixer.clipAction(old).crossFadeTo(next,.15,false);this.clip=name;}
  private booAnimation(name:string):void{const a=this.host.models[1].animations.find(a=>a.name===name);if(a){this.booMixer.stopAllAction();this.booMixer.clipAction(a).play();}}
  private visible(v:Vector3):boolean{const p=v.clone().project(this.camera);return p.z>-1&&p.z<1&&Math.abs(p.x)<.94&&Math.abs(p.y)<.88;}
  private feed(index:number):Vector3{return this.boss.getObjectByName('Feed_'+index)!.getWorldPosition(new Vector3());}
  private shoot(origin:Vector3,target:Vector3,hostile:boolean):void{if(this.shots.length>=64)return;const mesh=new Mesh(this.ball,hostile?this.red:this.green);mesh.position.copy(origin);this.scene.add(mesh);this.shots.push({mesh,velocity:target.clone().sub(origin).normalize().multiplyScalar(hostile?9:28),hostile,life:hostile?2.4:1.1});if(!hostile)this.shotsFired++;sfx.play(hostile?'enemyShoot':'shoot',.25);}
  private hurt(amount:number):void{if(this.dead||this.invulnerable>0||this.dashing)return;this.invulnerable=.55;this.injuries++;if(this.shielding&&this.charge>0){this.charge=Math.max(0,this.charge-amount*1.8);return;}this.life=Math.max(0,this.life-amount);sfx.play('hurt',.4);if(this.life===0){this.dead=true;this.input.clear();this.play('KnockdownRecover');const panel=document.createElement('section');panel.className='boarding-shop';const text=document.createElement('p');text.textContent='Your verified relays and upgrades are saved. Return to the latest safe route checkpoint.';const retry=document.createElement('button');retry.textContent='RETRY FOG MOON';bindSurfaceButton(retry,()=>{if(this.active)this.host.onRetry();},this.lifetime.signal);panel.append(text,retry);this.ui.appendChild(panel);}}
  private patrol(dt:number):void{let tells=this.guards.filter(g=>g.hp>0&&g.charge>0).length;for(const g of this.guards){if(g.hp<=0)continue;g.mesh.position.y=1.1+Math.sin(this.age*2+g.mesh.position.x)*.1;g.mesh.rotation.y=Math.atan2(this.hero.position.x-g.mesh.position.x,this.hero.position.z-g.mesh.position.z);if(g.charge>0){g.charge-=dt;if(g.charge<=0){g.tell.visible=false;tells--;if(this.visible(g.mesh.position)&&g.mesh.position.distanceTo(this.hero.position)<15)this.shoot(g.mesh.position,g.target,true);g.wait=2.8;}}else if((g.wait-=dt)<=0&&tells<2&&g.mesh.position.distanceTo(this.hero.position)<13&&this.visible(g.mesh.position)){g.charge=.9;g.target.copy(this.hero.position).y=1;g.tell.position.copy(g.target).y=.025;g.tell.scale.set(.8,1,.8);g.tell.visible=true;tells++;}}}
  private updateShots(dt:number):void{for(let i=this.shots.length-1;i>=0;i--){const b=this.shots[i],before=b.mesh.position.clone();b.life-=dt;b.mesh.position.addScaledVector(b.velocity,dt);if(b.hostile&&segmentSphere(before,b.mesh.position,this.hero.position.clone().add(new Vector3(0,1,0)),.5)){this.hurt(8);b.life=0;}else if(!b.hostile){const g=this.guards.find(g=>g.hp>0&&segmentSphere(before,b.mesh.position,g.mesh.position,.72));if(g){g.hp=Math.max(0,g.hp-12);this.hits++;b.life=0;if(!g.hp){g.mesh.visible=false;g.tell.visible=false;sfx.play('explode',.35);}}else if(this.started&&!this.restored)for(let feed=0;feed<3;feed++)if(segmentSphere(before,b.mesh.position,this.feed(feed),CITADEL.feedRadius)){if(this.battle.hit(feed,12))this.hits++;b.life=0;break;}}if(b.life<=0){this.scene.remove(b.mesh);this.shots.splice(i,1);}}}
  private updateHazards(dt:number):void{
    const ids=new Set(this.battle.hazards.map(h=>h.id));for(const [id,m] of this.hazards)if(!ids.has(id)){this.scene.remove(m);(m.material as MeshBasicMaterial).dispose();this.hazards.delete(id);}
    for(const h of this.battle.hazards){let m=this.hazards.get(h.id);if(!m){m=new Mesh(h.kind==='lane'?this.box:this.circle,new MeshBasicMaterial({color:0xff2200,transparent:true,opacity:.3,toneMapped:false,depthWrite:false}));this.hazards.set(h.id,m);this.scene.add(m);}const hot=h.tell===0;m.position.set(h.x,hot?.5:.035,h.z);m.scale.set(h.kind==='lane'?1.8:.8,h.kind==='lane'?hot?1:.025:1,h.kind==='lane'?20:.8);(m.material as MeshBasicMaterial).opacity=hot?.85:.25+.12*Math.sin(this.age*14);
      if(hot&&!h.hit&&(h.kind==='lane'?Math.abs(this.hero.position.x-h.x)<1.1&&Math.abs(this.hero.position.z-h.z)<10.3:surfaceSegmentHit({x:h.x-h.dx*dt,z:h.z-h.dz*dt},h,this.hero.position,.75))){this.hurt(h.kind==='lane'?18:12);if(h.kind==='seeker')h.hit=true;}
    }
  }
  private recolor(root:Group,green:boolean):void{root.traverse(o=>{if(o instanceof Mesh){const map=(m:import('three').Material)=>m.name.includes('hostile #FF2200')?green?this.green:this.red:m;o.material=Array.isArray(o.material)?o.material.map(map):map(o.material);}});}
  private refresh():void{
    for(let i=0;i<2;i++)if(this.solved(i))this.recolor(this.host.models[3].scene.getObjectByName('Relay_'+FOG_RELAYS[i].id) as Group,true);
    if(this.restored&&!this.factionApplied){this.factionApplied=true;this.recolor(this.boss,true);this.recolor(this.host.models[3].scene,true);}
  }
  private finish():void{this.pending=true;this.input.clear();for(const b of this.shots)this.scene.remove(b.mesh);this.shots.length=0;this.battle.hazards.length=0;this.updateHazards(0);this.talk('restored',()=>{const r=completeFogCitadel(this.host.save,this.battle.hp===0);if(!r.ok)return false;this.restored=true;this.pending=false;this.say('PUBLIC SIGNALS RESTORED · Boo recruited. Bullion Reach discovered.');return true;});}
  update(dt:number):void{
    if(!this.active)return;this.comms.update(dt);if(this.talking&&!this.comms.active){this.input.clear();this.updateCamera(true);}this.talking=this.comms.active;
    if(this.comms.active){this.mixer.update(dt);this.booMixer.update(dt);this.updateCamera();this.paint();return;}if(this.paused||this.dead||this.pending||this.relayPanel){this.paint();return;}
    if(this.arrival>0){this.arrival=Math.max(0,this.arrival-dt);this.fighter.position.y=PARKED_HEIGHT+8*(this.arrival/4)**2;if(!this.arrival){this.hero.visible=true;this.input.clear();}this.updateCamera();this.paint();return;}
    if(!this.restored&&!this.started&&this.solved(0)&&this.solved(1)&&this.hero.position.z<-18){this.talk('citadel',()=>{this.started=true;return true;});return;}
    this.age+=dt;this.invulnerable=Math.max(0,this.invulnerable-dt);this.repairCooldown=Math.max(0,this.repairCooldown-dt);this.fireClock-=dt;if(this.noticeClock>0&&(this.noticeClock-=dt)<=0)this.notice.textContent='';
    const move=this.input.move;this.dashing=this.dash.active;const burst=this.dash.update(dt);this.reveal.update(dt);const next=slideSurface(this.hero.position,this.dashing?burst.x:move.x*5.8*dt,this.dashing?burst.z:move.y*5.8*dt,p=>fogClear(p)&&!withinFootprint(p,this.fighterOutline));this.hero.position.x=next.x;this.hero.position.z=next.z;if(Math.hypot(move.x,move.y)>.1)this.hero.rotation.y=Math.atan2(move.x,move.y);
    for(let i=0;i<2;i++)if(this.reveal.reaches(this.hero.position,FOG_RELAYS[i]))this.learned.add(i);this.battle.update(dt,this.hero.position,this.started&&this.hero.position.z<-16);this.battle.identify(this.reveal.reaches(this.hero.position,this.feed(this.battle.trueFeed)));
    this.scene.updateMatrixWorld(true);const targets=this.guards.filter(g=>g.hp>0).map(g=>g.mesh.position);if(this.started&&!this.restored)targets.push(this.feed(this.battle.identified?this.battle.trueFeed:1));const target=targets.filter(p=>p.distanceTo(this.hero.position)<14&&this.visible(p)).sort((a,b)=>a.distanceToSquared(this.hero.position)-b.distanceToSquared(this.hero.position))[0];
    if(this.input.firing&&target){this.hero.rotation.y=Math.atan2(target.x-this.hero.position.x,target.z-this.hero.position.z);if(this.fireClock<=0){this.hero.updateMatrixWorld(true);this.shoot(this.hero.getObjectByName('Hand_R')!.getWorldPosition(new Vector3()),target,false);this.fireClock=.22+Math.max(-.05,this.fireClock);}}
    this.play(this.dashing?'Dodge':this.input.firing&&target?'AimFire':Math.hypot(move.x,move.y)>.1?'Run':'Idle');this.mixer.update(dt);this.booMixer.update(dt);this.patrol(dt);this.updateShots(dt);this.updateHazards(dt);
    this.charge=Math.max(0,Math.min(100,this.charge+(this.shielding?-14:18)*dt));if(this.charge===0)this.shielding=false;this.shield.visible=this.shielding||this.dashing;this.shield.position.copy(this.hero.position).y+=1;
    this.revealRing.visible=this.reveal.remaining>0;this.revealRing.position.copy(this.hero.position).y=.04;this.revealRing.scale.setScalar(15*(1-this.reveal.remaining/5));this.targetRing.visible=this.battle.identified&&!this.restored;this.targetRing.position.copy(this.feed(this.battle.trueFeed)).z+=1.4;
    for(let i=0;i<3;i++)this.boss.getObjectByName('Reflector_'+i)!.rotation.y=this.restored?0:Math.sin(this.age*.5+i)*.3;
    if(this.dead){this.paint();return;}if(!this.restored&&this.battle.hp===0){this.finish();return;}this.updateCamera();if((this.hudClock+=dt)>.1){this.hudClock=0;this.paint();}
  }
  private updateCamera(snap=false):void{const width=this.host.root.clientWidth,height=this.host.root.clientHeight,aspect=width/Math.max(1,height);this.camera.aspect=aspect;this.camera.clearViewOffset();if(this.comms.active&&this.talkKind==='boo')frameConversation(this.camera,this.hero.position,this.boo.position,width,height);else if(this.comms.active)frameWarden(this.camera,this.bossBounds,width,height);else{const scale=aspect<1?1.12:1,goal=this.hero.position.clone().add(new Vector3(0,16*scale,17*scale));if(snap)this.camera.position.copy(goal);else this.camera.position.lerp(goal,.16);this.camera.lookAt(this.hero.position.x,0,this.hero.position.z-2);}this.camera.updateProjectionMatrix();this.camera.updateMatrixWorld(true);this.sun.position.copy(this.hero.position).add(new Vector3(-18,32,12));this.sun.target.position.copy(this.hero.position);this.sun.target.updateMatrixWorld(true);}
  private paint():void{
    this.ui.dataset.conversation=String(this.comms.active);this.pauseButton.textContent=this.paused?'RESUME':'PAUSE';this.shieldButton.textContent=this.shielding?'SHIELD ON':'SHIELD';this.repairButton.textContent=this.repairCooldown>0?`REPAIR ${Math.ceil(this.repairCooldown)}s`:'REPAIR';this.repairButton.disabled=this.life>=100||this.repairCooldown>0;this.dashButton.textContent=this.dash.cooldown>0?`DASH ${Math.ceil(this.dash.cooldown)}s`:'DASH';this.dashButton.disabled=this.dash.cooldown>0;this.revealButton.hidden=!this.met;this.revealButton.textContent=this.reveal.cooldown>0?`REVEAL ${Math.ceil(this.reveal.cooldown)}s`:'REVEAL';this.revealButton.disabled=this.reveal.cooldown>0;
    this.status.textContent=`FOG MOON · RELAY CANYON\nVITALS ${Math.ceil(this.life)} · SHIELD ${Math.ceil(this.charge)}${this.paused?' · PAUSED':''}\n${this.restored?'PUBLIC SIGNALS RESTORED':this.started?`CITADEL ${this.battle.hp}/${CITADEL.hp} · ${this.battle.open?this.battle.identified?'VERIFIED '+FEED_NAMES[this.battle.trueFeed]:'REVEAL NOW':'REFLECTORS SEALED'}`:`VERIFIED RELAYS ${Number(this.solved(0))+Number(this.solved(1))}/2`}`;
    this.hint.textContent=this.restored?'Return south to the fighter. Boo and Reveal remain with you.':!this.met?'Clear the red drones and meet Boo at the scout shelter.':!this.solved(0)?'WEST ARCHIVE · Follow the west shelf. Reveal the genuine feed.':!this.solved(1)?'EAST UPLINK · Follow the north loop; trace the verified source.':this.started?'Reveal while the reflectors are open. Blast the green target ring around the red feed. Dodge red lanes.':'Both links verified. Approach the Citadel to the north.';
    this.interactButton.textContent=nearFog(this.hero.position,FOG_LANDING)?'WARSHIP':nearFog(this.hero.position,BOO_POSITION)?'BOO':'INTERACT';
    const nearby=FOG_RELAYS.findIndex(r=>Math.hypot(this.hero.position.x-r.x,this.hero.position.z-r.z)<15);for(let i=0;i<3;i++){const label=this.feedLabels[i];label.hidden=this.comms.active||this.paused||this.relayPanel!==null||nearby<0||!this.learned.has(nearby)&&!this.solved(nearby);if(!label.hidden){const r=FOG_RELAYS[nearby],node=this.host.models[3].scene.getObjectByName(`Relay_${r.id}_Feed_${i}`)!;const p=node.getWorldPosition(new Vector3()).add(new Vector3(0,.9,0)).project(this.camera);label.hidden=Math.abs(p.x)>1||Math.abs(p.y)>1||p.z>1;label.style.left=(p.x*.5+.5)*100+'%';label.style.top=(-p.y*.5+.5)*100+'%';label.textContent=(i===r.trueFeed?'✓ ':'× ')+['A △','B □','C ◇'][i];label.dataset.true=String(i===r.trueFeed);}}
    if(this.host.save.testSlot)Object.assign(this.ui.dataset,{position:JSON.stringify(this.hero.position.toArray()),life:String(this.life),shield:String(this.charge),paused:String(this.paused),dialogue:String(this.comms.active),met:String(this.met),relays:JSON.stringify([this.solved(0),this.solved(1)]),learned:JSON.stringify([...this.learned]),bossHP:String(this.battle.hp),bossAge:String(this.battle.age),bossOpen:String(this.battle.open),identified:String(this.battle.identified),trueFeed:String(this.battle.trueFeed),guards:JSON.stringify(this.guards.filter(g=>g.hp>0).map(g=>({sector:g.sector,hp:g.hp,position:g.mesh.position.toArray()}))),hazards:JSON.stringify(this.battle.hazards),shots:String(this.shotsFired),hits:String(this.hits),injuries:String(this.injuries),firing:String(this.input.firing),revealCooldown:String(this.reveal.cooldown),revealRemaining:String(this.reveal.remaining),dashCooldown:String(this.dash.cooldown),dashing:String(this.dashing),restored:String(this.restored),victoryPending:String(this.pending),arrival:String(this.arrival)});
  }
  render():void{this.camera.aspect=this.host.root.clientWidth/Math.max(1,this.host.root.clientHeight);this.camera.updateProjectionMatrix();this.host.renderer.render(this.scene,this.camera);if(this.host.save.testSlot)Object.assign(this.ui.dataset,{triangles:String(this.host.renderer.info.render.triangles),calls:String(this.host.renderer.info.render.calls),geometries:String(this.host.renderer.info.memory.geometries),textures:String(this.host.renderer.info.memory.textures)});}
  dispose():void{this.active=false;this.input.dispose();this.comms.dispose();this.lifetime.abort();this.mixer.stopAllAction();this.mixer.uncacheRoot(this.hero);this.booMixer.stopAllAction();this.booMixer.uncacheRoot(this.boo);disposeObject(this.scene);this.ui.remove();}
}
